### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by justinsalamon** [marl/jams#90]
Trying to run [this](https://github.com/justinsalamon/audio_to_midi_melodia) script (see ```save_jams``` method) as follows:
```bash
python audio_to_midi_melodia.py ~/datasets/melody/mirex05/audio/train05.wav train05.mid 60 --smooth 0.25 --minduration 0.1 --jams
```
And getting the following error upon trying to save a JAMS file:
```
Traceback (most recent call last):
  File "audio_to_midi_melodia.py", line 176, in <module>
    audio_to_midi_melodia(args.infile, args.outfile, args.bpm, smooth=args.smooth, minduration=args.minduration, savejams=args.jams)
  File "audio_to_midi_melodia.py", line 158, in audio_to_midi_melodia
    save_jams(jamsfile, notes, track_duration)
  File "audio_to_midi_melodia.py", line 30, in save_jams
    jam.save(jamsfile)
  File "/Users/justin/dev/jams/jams/core.py", line 1186, in save
    self.validate(strict=strict)
  File "/Users/justin/dev/jams/jams/core.py", line 1216, in validate
    valid = super(JAMS, self).validate(strict=strict)
  File "/Users/justin/dev/jams/jams/core.py", line 478, in validate
    raise SchemaError(str(invalid))
  File "/Library/Python/2.7/site-packages/jsonschema/exceptions.py", line 35, in __str__
    return unicode(self).encode("utf-8")
  File "/Library/Python/2.7/site-packages/jsonschema/exceptions.py", line 39, in __unicode__
    self.validator, self.validator_value, self.instance, self.schema,
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Not entirely sure what I'm doing wrong...? (running jams v0.2.0 on python 2.7)

**Comment by bmcfee** [comment]
It looks like your values don't pass validation.  Can you print out `midi_an.data`?

**Comment by justinsalamon** [comment]
```
              time        duration  value confidence
0  00:00:00.211882 00:00:00.153832     62        NaN
1  00:00:00.420862 00:00:00.609524     64        NaN
2  00:00:01.233560 00:00:00.208980     59        NaN
3  00:00:01.503492 00:00:00.229297     57        NaN
4  00:00:01.787937 00:00:01.355465     60        NaN
5  00:00:04.176689 00:00:00.235102     54        NaN
6  00:00:04.574331 00:00:00.365714     55        NaN
7  00:00:05.099683 00:00:00.229297     57        NaN
8  00:00:05.389932 00:00:00.357007     60        NaN
9  00:00:05.752744 00:00:00.365714     62        NaN
10 00:00:06.118458 00:00:00.119002     63        NaN
11 00:00:06.237460 00:00:01.256780     64        NaN
12 00:00:07.601633 00:00:00.182857     67        NaN
13 00:00:08.019592 00:00:00.101587     62        NaN
14 00:00:08.164717 00:00:00.136417     64        NaN
15 00:00:08.321451 00:00:00.905578     62        NaN
16 00:00:09.604354 00:00:00.162540     63        NaN
17 00:00:09.766893 00:00:00.255419     64        NaN
18 00:00:11.270385 00:00:00.182857     62        NaN
19 00:00:11.537415 00:00:00.150930     60        NaN
20 00:00:11.694150 00:00:00.716916     60        NaN
21 00:00:14.169977 00:00:00.101587     62        NaN
22 00:00:14.318005 00:00:00.159637     64        NaN
23 00:00:14.532788 00:00:00.644354     60        NaN
24 00:00:15.188753 00:00:00.264127     58        NaN
25 00:00:15.464490 00:00:01.146485     60        NaN
26 00:00:16.610975 00:00:00.162540     61        NaN
27 00:00:16.773515 00:00:00.223492     60        NaN
28 00:00:17.017324 00:00:00.394739     62        NaN
29 00:00:17.412063 00:00:00.171247     63        NaN
30 00:00:17.583311 00:00:00.179955     64        NaN
31 00:00:17.763265 00:00:00.304762     67        NaN
32 00:00:18.068027 00:00:00.362812     69        NaN
33 00:00:18.819773 00:00:00.119002     57        NaN
34 00:00:19.008435 00:00:00.757551     59        NaN
35 00:00:19.899501 00:00:00.682086     57        NaN
36 00:00:20.610612 00:00:00.325079     59        NaN
37 00:00:20.935692 00:00:00.383129     60        NaN
38 00:00:21.330431 00:00:00.284444     62        NaN
39 00:00:21.670023 00:00:00.371519     64        NaN
40 00:00:22.090884 00:00:00.113197     68        NaN
41 00:00:22.204082 00:00:00.693696     69        NaN
42 00:00:22.897778 00:00:00.223492     68        NaN
43 00:00:23.121270 00:00:00.174150     69        NaN
44 00:00:23.547937 00:00:00.238005     65        NaN
45 00:00:24.909206 00:00:00.177052     69        NaN
46 00:00:25.086259 00:00:00.258322     68        NaN
47 00:00:25.663855 00:00:00.824308     64        NaN
48 00:00:26.935147 00:00:00.525351     71        NaN
49 00:00:27.460499 00:00:00.197370     72        NaN
50 00:00:27.657868 00:00:00.415057     71        NaN
51 00:00:29.837642 00:00:00.156735     63        NaN
52 00:00:29.994376 00:00:00.722721     64        NaN
53 00:00:30.722902 00:00:00.119002     62        NaN
54 00:00:31.245351 00:00:00.714014     59        NaN
55 00:00:31.959365 00:00:01.268390     60        NaN
56 00:00:33.227755 00:00:00.261224     59        NaN
57 00:00:33.488980 00:00:00.174150     60        NaN
58 00:00:33.663129 00:00:00.737234     59        NaN
```
Looks fine no?

**Comment by urinieto** [comment]
What is your pandas version? I had problems with `msaf` and the latest `pandas` version. See [this](https://github.com/urinieto/msaf/issues/14). The temporary workaround is to downgrade `pandas` to 0.16.2.

**Comment by justinsalamon** [comment]
I'm still on ```pandas``` 0.16.1

**Comment by bmcfee** [comment]
That's super weird, and yes, it looks fine.

Do the unit tests pass on your machine?

Everything works for me on pandas 0.17, but it also worked when I was on 0.16.2.

**Comment by justinsalamon** [comment]
I've re-installed ```jams``` and ```mir_eval``` from source (just in case). When I run nosetests (from the ```jams/jams/tests``` folder), I get:
```bash
justin$ nosetests
..................................................................................................................................................................................../usr/local/lib/python2.7/site-packages/pandas/tseries/timedeltas.py:55: RuntimeWarning: tp_compare didn't return -1 or -2 for exception
  value = value.astype('timedelta64[ns]', copy=False)
...................................................................................................................................................................................................................................................................................................................................................................................E...............................
======================================================================
ERROR: Failure: KeyError ('jams/tests/fixtures/schema')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/Users/justin/Documents/dev/jams/jams/tests/schema_test.py", line 64, in test_schema_local
    'schema'))
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 954, in resource_filename
    self, resource_name
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 1652, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 1673, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'jams/tests/fixtures/schema'

----------------------------------------------------------------------
Ran 583 tests in 16.151s

FAILED (errors=1)
```

**Comment by justinsalamon** [comment]
update: just upgraded my ```jsonschema``` from 2.30 to 2.5.1. Now getting a slightly more friendly error:
```bash
Traceback (most recent call last):
  File "audio_to_midi_melodia.py", line 183, in <module>
    audio_to_midi_melodia(args.infile, args.outfile, args.bpm, smooth=args.smooth, minduration=args.minduration, savejams=args.jams)
  File "audio_to_midi_melodia.py", line 165, in audio_to_midi_melodia
    save_jams(jamsfile, notes, track_duration)
  File "audio_to_midi_melodia.py", line 37, in save_jams
    jam.save(jamsfile)
  File "build/bdist.macosx-10.9-x86_64/egg/jams/core.py", line 1186, in save
  File "build/bdist.macosx-10.9-x86_64/egg/jams/core.py", line 1216, in validate
  File "build/bdist.macosx-10.9-x86_64/egg/jams/core.py", line 478, in validate
jams.exceptions.SchemaError: array([  6.90624574e-07,   6.71248301e-07,   6.26267763e-07, ...,
        -1.51549884e-07,  -1.41861761e-07,  -9.82652182e-08], dtype=float32) is not of type u'number'

Failed validating u'type' in schema[u'properties'][u'file_metadata'][u'properties'][u'duration']:
    {u'minimum': 0.0, u'type': u'number'}

On instance[u'file_metadata'][u'duration']:
    array([  6.90624574e-07,   6.71248301e-07,   6.26267763e-07, ...,
            -1.51549884e-07,  -1.41861761e-07,  -9.82652182e-08], dtype=float32)
```

**Comment by justinsalamon** [comment]
...and consequently I have found the problem: I was setting the ```jam.file_metadata.duration``` to something that wasn't a number. Three hips for improved error messages.

Closing.
